name: 'Release'

on:
  push:
    tags: ['*']

jobs:
  release:
    uses: zenhelix/ci-workflows/.github/workflows/gradle-plugin-release.yml@v3
    with:
      java-version: '17'
      publish-command: './gradlew :plugins:publishPlugins :plugins:aa_catalog:publish -Pversion=''${{ github.ref_name }}'''
    secrets: inherit
